services:
  app:
    build:
      context: .
      dockerfile: ./network-simulator/Dockerfile
    volumes:
      - ../../conda:/workspaces/conda:cached
      - ../../mamba:/workspaces/mamba:cached
      - ../:/workspaces/conda-libmamba-solver:cached
    cap_add:
      - NET_ADMIN
    depends_on:
      - repo

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  repo:
    build:
      context: ./network-simulator
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    volumes:
      # Mount a directory for serving package metadata
      - ./network-simulator/repodata:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    cap_add:
      - NET_ADMIN
